import { Router, Request, Response } from 'express';
import { authenticateJWT, requireWorkspaceMember } from '../middleware/auth';
import { generationService } from '../services/generation.service';
import { creditsService, CREDITS_COSTS } from '../services/credits.service';
import { WorkspaceModel } from '../models/schemas/Workspace.schema';
import { Workspace, ArchitectureData } from '../types';

const router = Router({ mergeParams: true });

// ─── GET /api/workspaces/:id/archspec ─────────────────────────────────────────
router.get('/:id/archspec', authenticateJWT, requireWorkspaceMember('viewer'), (req: Request, res: Response) => {
  const ws = req.workspace!;
  return res.json({ data: generateArchSpec(ws) });
});

// ─── POST /api/workspaces/:id/export ──────────────────────────────────────────
router.post('/:id/export', authenticateJWT, requireWorkspaceMember('editor'), async (req: Request, res: Response) => {
  const userId    = req.user!.userId;
  const workspace = req.workspace!;
  const { platform = 'github-actions' } = req.body;

  const deducted = await creditsService.deductCredits(userId, CREDITS_COSTS.CICD, { action: 'cicd_export' });
  if (!deducted) return res.status(402).json({ error: 'Insufficient credits' });

  try {
    const [cicdYaml, archspecYaml] = await Promise.all([
      generationService.generateCICDConfig(workspace.id, workspace.techStack, platform),
      Promise.resolve(generateArchSpec(workspace)),
    ]);

    // Persist the archspec for future reference
    await WorkspaceModel.findByIdAndUpdate(workspace.id, {
      $set: { archspecYaml, updatedAt: new Date() },
    });

    return res.json({
      data: {
        cicdYaml,
        archspecYaml,
        dockerfileHint: generateDockerfileHint(workspace.techStack),
        platform,
        message: 'CI/CD configuration generated successfully.',
      },
    });
  } catch (err) {
    await creditsService.addCredits(userId, CREDITS_COSTS.CICD, 'earn', { reason: 'cicd_failed_refund' });
    console.error('[Export] Error:', err);
    return res.status(500).json({ error: 'Export failed. Credits refunded.' });
  }
});

// ─── POST /api/workspaces/:id/fork ───────────────────────────────────────────
router.post('/:id/fork', authenticateJWT, async (req: Request, res: Response) => {
  const userId   = req.user!.userId;
  const sourceWs = await WorkspaceModel.findById(req.params.id).lean();

  if (!sourceWs) return res.status(404).json({ error: 'Workspace not found' });
  if (sourceWs.visibility !== 'public') {
    return res.status(403).json({ error: 'Can only fork public workspaces' });
  }

  const forked = new WorkspaceModel({
    ...sourceWs,
    _id: undefined,
    ownerId: userId,
    name: `${sourceWs.name} (Fork)`,
    collaborators: [],
    visibility: 'private',
    forkCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  await forked.save();
  await WorkspaceModel.findByIdAndUpdate(sourceWs._id, { $inc: { forkCount: 1 } });

  // Reward the original owner
  await creditsService.addCredits(sourceWs.ownerId, 20, 'earn', {
    reason: 'workspace_forked',
    forkedBy: userId,
  });

  return res.status(201).json({ data: forked });
});

// ─── Helpers ──────────────────────────────────────────────────────────────────

function generateArchSpec(ws: Workspace): string {
  const arch = ws.architectureData as unknown as ArchitectureData;
  const lines = [
    `# ArchSpec DSL — Generated by VisualArch AI`,
    `# Workspace: ${ws.name}`,
    ``,
    `name: "${ws.name}"`,
    `description: "${ws.description ?? ''}"`,
    `version: "1.0.0"`,
    ``,
    `tech_stack:`,
    ...ws.techStack.map(t => `  - ${t}`),
    ``,
    `services:`,
    ...arch.nodes.map(n =>
      `  - id: ${n.id}\n    label: "${n.label}"\n    layer: "${n.layer}"\n    description: "${n.description}"`
    ),
    ``,
    `connections:`,
    ...arch.edges.map(e =>
      `  - from: ${e.source}\n    to: ${e.target}\n    type: ${e.label ?? 'http'}`
    ),
  ];
  return lines.join('\n');
}

function generateDockerfileHint(techStack: string[]): string {
  const hasNode   = techStack.some(t => /node|next/i.test(t));
  const hasPython = techStack.some(t => /python|django|fastapi/i.test(t));

  if (hasNode) {
    return `FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 3000
CMD ["node", "dist/index.js"]
`;
  }

  if (hasPython) {
    return `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
`;
  }

  return `FROM ubuntu:22.04
WORKDIR /app
COPY . .
EXPOSE 3000
CMD ["/app/start.sh"]
`;
}

export default router;
